---
title: "Appendix"
author: ' '
date: ' '
output: word_document
---

In Appendix A, we provide the details for assessing the persistence
of a population with an integrodifference model and we discuss the
effect of the harvesting function on population persistence. In Appendix B, we provide the details for assessing population persistence with separable dispersal kernels. In Appendix C and D, we derive expressions for the critical harvesting rate and rate of environmental shift for Gaussian and sinuosoidal dispersal kernels. In Appendix E, we derive approximate expressions for these critical rates. In Appendix F, we parameterize our model for black rockfish (*Sebastes melanops*)in the California Current and demonstrate that results for parameters are qualitatively similar to results presented in the main text. In Appendix G we provide details on differences between small and large MPA simulations.

A) Determining stability
----------------------------
Let $n_t(x)$ be the number of adults at position $x$ at time $t$, let $k(x)$ be a dispersal kernel describingt the probability of a larva traveling a distance $x$, let $f(n)$ be the recruitment function describing the number of offspring that settle and survive in juvenile population of size $n$, let $R_0$ be the intrinsic growth rate of the population, and let $g(n)$ be the harvesting function describing the number of adults harvested from a population of size $n$. In the absence of harvesting, the integrodifference model describing the population over time is given by

$$n_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0f(n_t(y))dy \label{integro}$$

as described in (Zhou and Kot 2011). With the addition of harvesting, the model becomes

$$n_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g(f(n_t(y)))dy.$$

In evaluating persistence, we apply the methods of Zhou and Kot (2011) to the new model, Equation 2. A traveling pulse is a solution such that population size relative to location within the patch (rather than absolute position) is constant over time, i.e.

$$n^*(\overline{x}_t)\equiv n^*(x-ct)=n_t(x)$$

where $\overline{x}_t\equiv x-ct$ gives position relative to the patch.

The integrodifference Eq. 2 gives us an expression for $n^*$:

$$n^*(\overline{x}_{t+1})=n_{t+1}(x)$$

$$n^*(\overline{x}_{t+1})=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g(f(n_t(y)))dy$$

$$n^*(\overline{x}_{t+1})=\int_{-L/2+ct}^{L/2+ct}k(x-\overline{y}_t-ct)R_0g(f(n^*(\overline{y}_t)))dy$$

$$n^*(\overline{x}_{t+1})=\int_{-L/2+ct}^{L/2+ct}k(\overline{x}_t-\overline{y}_t)R_0g(f(n^*(\overline{y}_t)))dy$$

$$\Rightarrow n^*(\overline{x}_t-c)=\int_{-L/2+ct}^{L/2+ct}k(\overline{x}_t-\overline{y}_t)R_0g(f(n^*(\overline{y}_t)))dy$$

$$\Rightarrow n^*(\overline{x}_t)=\int_{-L/2}^{L/2}k(\overline{x}_t+c-\overline{y}_t)R_0g(f(n^*(\overline{y}_t)))d\overline y_t$$

As long as $f(0)=0$, there is a trivial solution to this problem where $n^*(\overline{x})\equiv 0$ for all $\overline{x}$, i.e., there is a trivial traveling pulse with no adults in it. If the trivial traveling pulse is unstable, even very small populations will persist or grow and avoid crashing back to the trivial pulse. To evaluate the stability of a traveling pulse, we introduce a small perturbation to the traveling pulse $n^*(\overline{x})$ and see if this perturbation grows or shrinks over time:

$$n_t(x)=n^*(\overline{x}_t)+\xi_t(x)$$

$$\Rightarrow \xi_{t+1}(x)=n_{t+1}(x)-n^*(\overline{x}_{t+1})$$

$$ \xi_{t+1}(x)=n_{t+1}(x)-n^*(\overline{x}_{t}-c)$$

$$\xi_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g(f(n_t(y)))dy-\int_{-L/2}^{L/2}k(\overline{x}_{t}-\overline{y}_t)R_0g(f(n^*(\overline{y}_t)))d\overline y_t \text{ using Eq. 3}$$

$$\xi_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g(f(n_t(y)))dy-\int_{-L/2+ct}^{L/2+ct}k(x-ct-(y-ct))R_0g(f(n^*(\overline{y}_t)))d\overline y_t$$

$$\xi_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g(f(n_t(y)))dy-\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g(f(n^*(\overline{y}_t)))d\overline y_t$$

$$\xi_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)\big(R_0g(f(n_t(y)))-R_0g(f(n^*(\overline{y}_t)))\big)dy$$

$$\xi_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0\big(g(f(n_t(y)))-g(f(n^*(\overline{y}_t)))\big)dy$$

$$\Rightarrow \xi_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g\prime (f(n^*(\overline{y})))f\prime (n^*(\overline{y}))(n_t(y)-n^*(\overline{y}_t))dy$$

by linearizing around the traveling pulse

$$\Rightarrow \xi_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g\prime (f(n^*(\overline{y})))f\prime(n^*(\overline{y}))\xi_t(y)dy$$

$$\Rightarrow \xi_{t+1}(x)=\int_{-L/2+ct}^{L/2+ct}k(x-y)R_0g\prime(0)f\prime(0)\xi_t(y)dy$$

if $n^*(\overline{x})=0$ and $f(0)=0$.

If we assume $\xi_t(x)=\lambda^tu(x-ct)$ for some $\lambda\in\mathbb{R}$ and $u:[-L/2,L/2]\to\mathbb{R}$, then the perturbation grows in time if and only if $\lambda >1$. Using Eq. 4, we can rewrite $\xi_{t+1}(x)$,

$$\lambda u(x-ct-c)=R_0g\prime(0)f\prime(0)\int_{-L/2+ct}^{L/2+ct}k(x-y)u(y-ct)dy$$

$$\Rightarrow \lambda u(\overline{x})=R_0g\prime (0)f\prime (0)\int_{-L/2}^{L/2}k(\overline{x}+c-\overline{y})u(\overline{y})dy$$

Define the integral operator 

$$\psi_f(u)(x)=R_0g\prime (0)f\prime (0)\int_{-L/2}^{L/2}k(x+c-y)u(y)dy.$$ 

Then the perturbation to the traveling pulse will satisfy

$$\psi_f(u)(x)=\lambda u(x)$$

$\lambda$ and $u$ are thus an eigenvalue and eigenfunction of the functional operator $\psi_f$. The trivial traveling pulse is unstable when the dominant eigenvalue of $\psi_f$ is greater than $1$.

The biomass in the equilibrium traveling wave depends on the specific functional forms of the harvesting function $g(n)$ and the recruitment function $f(n)$. However, the persistence of the population only depends on $R_0$, $g\prime (0)$ and $f\prime (0)$. In this paper, we only considered a proportional harvesting function, i.e. the amount of adults harvested obeyed $g(n)=(1-h)n$. For this function, $g\prime (0)=1-h$. For the recruitment function we considered, $f\prime(0)=1$.

B) Separable dispersal kernels
---------------------------------
It is not immediately obvious that the operator $\psi$ will have any eigenfunctions. However, Jentzsch’s theorem guarantees that there is an eigenfunction $u$, provided that the kernel $k$ satisfies some properties (Zhou and Kot 2011). Finding the eigenfunctions and eigenvalues is in general a hard problem to solve. It becomes easier if the kernel $k$ is separable, i.e., there are functions $a_n,b_n$ such that $k(x-y)=\sum_{n=1}^\infty a_n(x)b_n(y)$. In that case, Eq. 5 becomes

$$\lambda u(x)=R_0g\prime (0)f\prime (0)\sum_{n=1}^\infty\left( a_n(x)\int_{-L/2}^{L/2}b_n(y-c)u(y)dy\right)$$

$$\Rightarrow \lambda\int_{-L/2}^{L/2}b_k(x-c)u(x)dx=R_0g\prime (0)f\prime (0)\sum_{n=1}^{\infty}\left(\int_{-L/2}^{L/2}b_n(x-c)u(x)dx\right)\left(\int_{-L/2}^{L/2}a_n(y)b_k(y-c)dy\right)$$

for any $k$

$$\Rightarrow \lambda d_k=R_0g\prime (0)f\prime (0)\sum_{n=1}^\infty A_{nk}d_n$$

where

$$A_{nk}=\int_{-L/2}^{L/2}a_n(x)b_k(x-c)dx \text{ and } d_k=\int_{-L/2}^{L/2}b_k(x-c)u(x)dx$$

Finding the eigenvalues of Eq. 5 then reduces to finding the eigenvalues of the matrix comprised of entires $(A_{nk})_{n,k=1}^\infty$.

To find the equilibrium biomass, we rewrite Eq. 3 using the separable kernel as in (Latore et al.1998):

$$n^*(x)=\int_{-L/2}^{L/2}k(x+c-y)R_0g(f(n^*(y)))dy$$

$$n^*(x)= \int_{-L/2}^{L/2}\left(\sum_{n=1}^\infty a_n(x)b_n(y-c)\right)R_0g(f(n^*(y)))dy$$

$$n^*(x)=\sum_{n=1}^\infty a_n(x) \int_{-L/2}^{L/2}b_n(y-c)R_0g(f(n^*(y)))dy$$

If we define $m_n=\int_{-L/2}^{L/2}b_n(y-c)R_0g(f(n^*(y)))dy$ then we find that

$$n^*(x)=\sum_{n=1}^\infty m_na_n(x) \text { and }$$

$$m_n=\int_{-L/2}^{L/2}b_n(y-c)R_0g\left(f\left(\sum_{n=1}^\infty m_na_n(y)\right)\right)dy$$

Eq 7. allows us to find the $m_n$ numerically and we then find the total equilibrium biomass by integrating $n^*(x)$ over space.

C) Gaussian dispersal kernel
-----------------------------------
The Gaussian dispersal kernel is given by

$$k(x-y)=\frac{1}{2\sqrt{D\pi}}e^{\frac{-(x-y)^2}{4D}},$$ 

where $D$ is one half the variance of the kernel. This is a separable kernel with $a_n(x)=b_n(x)=\frac{1}{\sqrt{2n!\sqrt{D\pi}}}e^{-x^2/4D}\left(\frac{x}{\sqrt{2D}}\right)^n$ (Latore et al. 1998).

As a first approximation to $k$ we ignore all but the $0^{th}$ terms for $a_n$ and $b_n$ so that Eq. 6 becomes

$$\lambda d_0(c)&=R_0(1-h)A_{00}(c)d_0(c)$$

$$\Rightarrow \lambda=R_0(1-h)A_{00}(c)$$

$$\text{ where } A_{00}(c)=2\sqrt{2}\exp\left(\frac{-c^2}{8D}\right)\left[\text{erf}\left(\frac{L-c}{2\sqrt{2D}}\right)-\text{erf}\left(\frac{-L-c}{2\sqrt{2D}}\right)\right]$$

where $\text{erf}$ is the error function. The critical rate of environmental shift $c^*$ and the critical harvesting rate $h^*$ are those values of $c$ and $h$, respectively, that make $\lambda=1$.

D) Sinusoidal dispersal kernel
------------------------------------
The sinusoidal dispersal kernel is given by

$$k(x-y)=\left\{\begin{array}{ccccc}
\frac{w}{2}\cos(w(x-y)) & , & |x-y|\leq\frac{\pi}{2w}
\\ 0 & , & |x-y|>\frac{\pi}{2w}
\end{array}\right.$$ 

where $L$ is the length of the patch and we assume $\frac{\pi}{2w}>L,c<\frac{\pi}{2w}-L$.

In this case, $k(x-y)=\frac{w}{2}\cos(wx)\cos(w(y-c))+\frac{w}{2}\sin(wx)\sin(w(y-c))$ so that $A_{ij}$ and $d_i$ can be found for $i,j=1,2$ and Eq. 6 reduces to

$$\lambda^2-\left(\frac{R_0(1-h)wL}{2}\cos(wc)\right)\lambda+\frac{R_0^2(1-h)^2}{16}\left(w^2L^2-\sin^2(wL)\right)=0.$$

If we solve for $\lambda$,we find

$$\lambda=(1-h)R_0\left[\frac{wL\cos(wc)}{4}+\frac{1}{4}\sqrt{\sin^2(wL)-w^2L^2\sin^2(wc)}\right].$$

Zhou and Kot (2011) solve for the critical speed, $c^*$, at which the
population will be driven extinct:

$$c^*=c^*(R_0)=\frac{1}{w}\cos^{-1}\left[\frac{16+R_0^2(1-h)^2(w^2L^2-\sin^2(wL))}{8R_0(1-h)wL}\right].$$

In our model, we can additionally solve for the critical harvesting
rate, $h^*$, at which the population will be driven extinct:

$$h^*=1-\frac{1}{R_0}\cdot\frac{4wL}{w^2L^2-\sin^2(wL)}\left[\cos(wc)-\sqrt{\cos^2(wc)-1+\frac{\sin^2(wL)}{w^2L^2}}\right]$$

E) Approximate critical harvesting proportions
--------------------------------------------------------
We will use the following Taylor series to make approximations of the critical harvesting proportions under the two dispersal kernels:

$$\cos(x)=1-\frac{x^2}{2}$$

$$\cos^2(x)=1-x^2$$

$$\sin^2(x)=x^2-\frac{x^4}{3}$$

$$erf(x)=\frac{2}{\sqrt{\pi}}(x-\frac{x^3}{3})$$

$$\exp(x)=1+x+\frac{x^2}{2}$$

For the Gaussian kernel we found

$$h^*=1-\frac{2\sqrt{2}\exp\left(\frac{c^{2}}{8D}\right)}{R_0\left[erf\left(\frac{L-c}{2\sqrt{2D}}\right)-erf\left(\frac{-L-c}{2\sqrt{2D}}\right)\right]}$$

Using the Taylor series and the fact that $D=\frac{\sigma^2}{2}$ where $\sigma^2$ is the variance of the exponential kernel,

$$h^*\sim 1-\frac{\sqrt{2\pi}(1+\frac{c^2}{8D}+\frac{c^4}{128D^2})}{R_0\sqrt{\pi}\left[\frac{L-c}{2\sqrt{2D}}-\frac{(L-c)^3}{3(2\sqrt{2D})^3}-\frac{-L-c}{2\sqrt{2D}}+\frac{(-L-c)^3}{3(2\sqrt{2D})^3)}\right]}$$

$$h^*= 1-\frac{1}{R_0}\cdot\frac{3\sqrt{2\pi}}{8L}\frac{(32\sigma^4+8c^2\sigma^2+c^4)}{\sigma\left(12\sigma^2-(L^2+3c^2)\right)}$$

For the sinusoidal kernel we found

$$h^*=1-\frac{1}{R_0}\cdot\frac{4wL}{w^2L^2-\sin^2(wL)}\left[\cos(wc)-\sqrt{\cos^2(wc)-1+\frac{\sin^2(wL)}{w^2L^2}}\right]$$

Using the Taylor series and the fact that $w=\frac{\sqrt{\frac{\pi^2}{4}-2}}{\sigma}$ where $\sigma^2$ is the variance of the sinusoidal kernel,

$$h^*\sim 1-\frac{1}{R_0}\cdot\frac{12wL}{w^4L^4}\left[1-\frac{w^2c^2}{2}-\sqrt{1-w^2c^2-\frac{w^2L^2}{3}}\right]$$

$$h^*=1-\frac{1}{R_0}\cdot\frac{4\sqrt{3}}{L^3(\pi^2-8)^{3/2}}\cdot\sigma\left[8\sqrt{3}\sigma^2-(\pi^2-8)\sqrt{3}c^2-4\sigma\sqrt{12\sigma^2-(\pi^2-8)(3c^2+L^2)}\right]$$

In the case of both kernels, the critical harvesting proportion can be approximated by a function that looks like

$$h^*\sim1- \frac{1}{R_0}\cdot p(L)q(\sigma^2,c^2,L^2+3c^2)$$

where $p(L)$ is a decreasing function of the length of the viable patch $L$.

F) California Current Black Rockfish Parameterization
---------------------------------------------------------
We parameterize our model for black rockfish (*Sebastes melanops*) in the California Current, with MPAs of spacing and width qualitatively similar to those in the Marine Life Projection Act (MLPA), and with a maximum climate velocity equal to that observed empirically. The parameters and references are provided in Table A1.

Our results with this parameterization are qualitatively similar to the results presented in the main text. In particular, we find the same negative relationship between critical harvesting rate $h^*$ and the climate velocity $c$ (Figure A1) and an essentially additive interaction between the effects of the two stressors on biomass (Figure A2). Additionally, our black rockfish parameterization has the same counterintuitive result that MPAs from which effort is displaced (rather than eliminated) can be worse than no MPA at all (compare Figure A4A and A4D).

G) Protected Area fluctuations
---------------------------------
After the simulations come to equilibrium, the fluctuations in total biomass per generation fluctuate more in reserves that are larger and spaced farther apart than simulations in which the reserves that are smaller and more closely spaced (Figure A3). The large reserves have a slightly larger average population, however large reserves here can induce fluctuations of biomass even in deterministic simulations. Thus we expect if reproduction was stochastic, large reserves spaced far apart would be more likely to result in extinction of the population than more closely spaced, smaller reserves. We find the same effect regardless of whether or not effort remains constant or is removed from the system.
